### ISSUE TITLE
热点更新时间有点早

### ISSUE THREAD

**Issue by QMike0** [muhanstudio/siyuan-widget-Host-list#1]
当前时间坐标2023.11.26，各个网站热点更新时间大多数都在一周之前，感觉时间太早的话就不能算热点了

![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/d680b0c2-12bb-4005-8f6e-c86263a80173)
![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/30a344f4-b112-4d99-9299-2a519d6e2550)
![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/c0c646ba-f9cc-44f3-b695-89ec47ed91cd)

央视要闻甚至是2019年的新闻哈哈，今夕是何年
![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/f8355400-8b69-44d4-a0ea-ad829a900cb0)

**Comment by muhanstudio** [comment]
检查了一下原来是我采集数据的程序停了，现在可以了，刷新即可看到最新数据

**Comment by QMike0** [comment]
好嘞，谢谢佬~

央视新闻可以也更新一下嘛，这个还是2019年9月5日的热点
![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/cfbca09b-c311-49eb-9911-f34f413a69a7)

**Comment by muhanstudio** [comment]
这个应该是采集规则失效了，当我有空更新吧

**Comment by QMike0** [comment]
嗯嗯好呢
