### ISSUE TITLE
挂件好像不能用了

### ISSUE THREAD

**Issue by QMike0** [muhanstudio/siyuan-widget-Host-list#2]
佬，挂件好像g了：
![image](https://github.com/muhanstudio/siyuan-widget-Host-list/assets/43239563/fd3fdda3-19ff-44cd-a63c-cfd8b9b8b83f)

**Comment by muhanstudio** [comment]
已经修复，服务器python项目寄了，导致没办法获取数据
不过你可以去社区的折腾群催更一下群主的rsshub，他那个上架了我就把这个下架了

**Comment by QMike0** [comment]
好的~
群主的大活一直憋的都比较慢，佛系等哈哈
